export const regionMappings = {
    "BASIN" : [0,3],
    "SPEAKING" : [-0.75,2.5], 
    "HOWL" : [0.75,2.5],
    "REACHING" : [-0,2],
    "CALLUMS" : [-1.5,2],
    "CLANSHEAD" : [1.5,2],
    "NEVISH" : [-2.25,1.5],
    "MOORS" : [-0.75,1.5],
    "VIPER" : [0.75,1.5],
    "MORGENS" : [2.25,1.5],
    "CALLAHANS" : [0,1], 
    "STONECRADLE": [-1.5,1], 
    "WEATHERED": [1.5,1], 
    "OARBREAKER": [-2.25,0.5],
    "LINN": [-0.75,0.5],
    "MARBAN": [0.75,0.5],
    "GODCROFTS": [2.25,0.5],
    "DEADLANDS" : [0,0],
    "FARRANAC": [-1.5,0], 
    "ENDLESS": [1.5,0], 
    "FISHERMANS": [-2.25,-0.5], 
    "LOCH": [-0.75,-0.5], 
    "DROWNED": [0.75,-0.5], 
    "TEMPEST": [2.25,-0.5],
    "UMBRAL" : [0,-1],
    "WESTGATE": [-1.5,-1], 
    "ALLODS": [1.5,-1], 
    "ORIGIN": [-2.25,-1.5], 
    "HEARTLANDS": [-0.75,-1.5], 
    "SHACKLED": [0.75,-1.5], 
    "FINGERS": [2.25,-1.5],
    "GREATMARCH" : [0,-2],
    "ASHFIELDS": [-1.5,-2], 
    "TERMINUS": [1.5,-2],
    "REDRIVER": [-0.75,-2.5], 
    "ACRITHIA": [0.75,-2.5],
    "KALOKAI": [0,-3],
}

export const regionNames = {
    "BASIN" : "Basin Sionnach",
    "SPEAKING" : "Speaking Woods", 
    "HOWL" : "Howl County",
    "REACHING" : "Reaching Trail",
    "CALLUMS" : "Callums Cape",
    "CLANSHEAD" : "Clanshead Valley",
    "NEVISH" : "Nevish Line",
    "MOORS" : "The Moors",
    "VIPER" : "Viper Pit",
    "MORGENS" : "Morgens Crossing",
    "CALLAHANS" : "Callahans Passage", 
    "STONECRADLE": "Stonecradle", 
    "WEATHERED": "Weathered Expanse", 
    "OARBREAKER": "The Oarbreaker Isles",
    "LINN": "The Linn of Mercy",
    "MARBAN": "Marban Hollow",
    "GODCROFTS": "Godcrofts",
    "DEADLANDS" : "Deadlands",
    "FARRANAC": "Farranac Coast", 
    "ENDLESS": "Endless Shore", 
    "FISHERMANS": "Fishermans Row", 
    "LOCH": "Loch Mor", 
    "DROWNED": "The Drowned Vale", 
    "TEMPEST": "Tempest Island",
    "UMBRAL" : "Umbral Wildwood",
    "WESTGATE": "Westgate", 
    "ALLODS": "Allods Bight", 
    "ORIGIN": "Origin", 
    "HEARTLANDS": "The Heartlands", 
    "SHACKLED": "Schackled Chasm", 
    "FINGERS": "The Fingers",
    "GREATMARCH" : "Great March",
    "ASHFIELDS": "Ash Fields", 
    "TERMINUS": "Terminus",
    "REDRIVER": "Red River", 
    "ACRITHIA": "Acrithia",
    "KALOKAI": "Kalokai",
}